Update readme.md
benjojo/dubstep-data pull request #1
Opened 2018-04-13 23:16 UTC by JordanHaigh

Added sections on how to run program and required packages

2018-04-13 23:48 UTC, benjojo requested changes

2018-04-13 23:48 UTC, benjojo commented on README.md
> +Aqcuire repos:
Acquire :)

2018-04-13 23:48 UTC, benjojo commented on README.md
> +cat in.f64.data | tee sound | ./decode -input /dev/stdin
the `sound` part is actually just a demo trick, If you want the `tee sound` thing to work, you need to also run 

```
$ mkfifo sound
$ ffplay -f f64le -ar 44100 -ac 1 -i sound &
```

before you do the final `cat`

2018-04-13 23:48 UTC, benjojo commented
Thanks for pulling this together, there are a few little things, but other than that! thanks for the docs!

2018-04-14 00:22 UTC, JordanHaigh commented
Fixed :)

2018-04-14 00:23 UTC, merged

2018-04-14 00:23 UTC, benjojo commented
Thanks!